### ISSUE TITLE
Desert wells spawning in loot areas?

### ISSUE THREAD

**Issue by nikidash** [YUNG-GANG/YUNGs-Better-Desert-Temples#1]
I don't know if this is intentional, but there seems to be desert wells or something similar spawning in the loot chambers. With the mining fatigue it can make navigating the areas very annoying, several times already i've had to blast with tnt the entrance to one of the two loot rooms because a well spawned the wrong way and was completely blocking access to the area.

**Comment by yungnickyoung** [comment]
There is a small room shaped like a vanilla desert well as a little easter egg. But you can just crouch walk through it - no need to blast w/ TNT
