### ISSUE TITLE
Game Crash in Better Desert Temple

### ISSUE THREAD

**Issue by EL-R1** [YUNG-GANG/YUNGs-Better-Desert-Temples#14]
https://mclo.gs/UJXaVF7

I have this crash report from my server and i was on a pyramid with traps and lot of candles
It crash the game when trap are triggered

This structure > https://www.youtube.com/watch?v=TpkTeTeDKJo

**Comment by yungnickyoung** [comment]
This doesn't appear to be related to this mod. It appears to be this issue with Hexerei: https://github.com/JoeFoxe/Hexerei-1.18/issues/68
