### ISSUE TITLE
Server crashes when solving puzzle

### ISSUE THREAD

**Issue by rhys-saldanha** [YUNG-GANG/YUNGs-Better-Desert-Temples#15]
I've raised an issue against the FTB modpack I'm running: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2324

Please see the above issue for more details and a link to the error log. In short, whenever I solve one of the 3 puzzles in the first layer of the pyramid, the server crashes!

**Comment by yungnickyoung** [comment]
Seems to be a duplicate of #14 , which in turn is caused by https://github.com/JoeFoxe/Hexerei-1.18/issues/68

**Comment by Gbergz** [comment]
Still an issue.
