### ISSUE TITLE
Vanilla structures spawning inside of temples

### ISSUE THREAD

**Issue by ThatSava** [YUNG-GANG/YUNGs-Better-Desert-Temples#16]
## Mod version:
2.2.1
## Api version:
3.8.2
## Problem:
In some worlds, vanilla wells can spawn in temples and prevent progress.
## How to replicate:
Make a world with the following seed: `2591626919953876320`
Teleport to following coordinates: -847 58 4335
You should be in a temple basement. If you try to progress the intended way, you will quickly find a vanilla well that is stopping you from continuing, this is easier seen in spectator mode. Attached is the image of following behavior.
![Vanilla well in the middle of temple](https://user-images.githubusercontent.com/3749778/214830841-fe38411c-fc02-4dc6-a72c-7813ca36075b.png)
## Suggested fix:
As I haven't done a lot with structures, I can't really offer a concise fix, but what I would look into is making a mixin that checks the base coordinates of vanilla structures before spawning them, and preventing them from spawning if the coordinates overlap with temple coordinates.

**Comment by yungnickyoung** [comment]
This is actually a fairly rare piece that can spawn as part of the temple, intended as a reference to vanilla desert wells lol

**Comment by ThatSava** [comment]
Huh, we were unsure if this is intended behavior on ftb legend of the eyes discord. I assumed it was not since you can't progress through it without breaking blocks. And, well, breaking blocks is not that fun with mining fatigue.

**Comment by yungnickyoung** [comment]
You should be able to crouch walk through the middle

**Comment by ThatSava** [comment]
I am going to defend by staying silent. Thanks
