### ISSUE TITLE
crash due to conflict w/ Cloth Config API

### ISSUE THREAD

**Issue by Ch4mp10** [YUNG-GANG/YUNGs-Better-Desert-Temples#26]
Not exactly sure what's going on here but there seems to be a conflict with this api. It has worked well for me in the past with no issues. I know that this is a dependency so I'm not sure what's wrong. Sorry I can't be more specific, I'm not much of a coder. Any advice on a solution would be greatly appreciated. Thanks

[crash-2023-09-17_19.25.15-client.txt](https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/files/12643983/crash-2023-09-17_19.25.15-client.txt)
[crash-2023-09-17_19.18.29-client.txt](https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/files/12643984/crash-2023-09-17_19.18.29-client.txt)
[crash-2023-09-17_20.01.49-client.txt](https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/files/12643986/crash-2023-09-17_20.01.49-client.txt)

**Comment by yungnickyoung** [comment]
It looks like your config got corrupted. It happens from time to time, not sure why. Try deleting the config files for any of my mods you're using and relaunch the game

**Comment by Ch4mp10** [comment]
Yep, that's what happened. Looks like quite a few config files got corrupted. Thank you for your help.
