### ISSUE TITLE
Pharoah's head crashing game (mod conflict)

### ISSUE THREAD

**Issue by Zizou-Olympia** [YUNG-GANG/YUNGs-Better-Desert-Temples#28]
As the title says, the Pharoah's head is crashing my game, specifically when my mouse goes over it in the inventory UI, unfortunately meaning I can't take it out of my inventory either.

After testing, I have found that it is a problem that occurs if the mod Toggle Enchantments, one which I use so I don't have to carry two different pickaxes, is enabled. Is it possible that the head has an enchantment that causes this problem, or is this just an unresolvable conflict?

**Comment by SiverDX** [comment]
post log

**Comment by Zizou-Olympia** [comment]
Here's the link to the log so it doesn't make this box unnecessarily big: https://paste.ee/p/63jeb

While I'm not exactly code-savvy, I think I've narrowed it down to a different mod, the aforementioned Toggle Enchantments, as people who use that are having the same issue with other mods.

**Comment by SiverDX** [comment]
nothing that could be done here really, the head is just a normal textured head

https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/blob/9c193f8fb12190833924503abd4f1e60aba5bfa2/Common/src/main/resources/data/betterdeserttemples/advancements/temple_clear.json#L32

there seems to be some config you can disable though

https://github.com/Dplayend/Toggle-Enchantments/blob/1b49206b3179ffed41cd3822871141eb16b0de53/src/main/java/com/dplayend/togenc/mixin/MixItem.java#L31C28-L31C28
