### ISSUE TITLE
Fire wont start after solving puzzles

### ISSUE THREAD

**Issue by Terekyy** [YUNG-GANG/YUNGs-Better-Desert-Temples#4]
Solving puzzles wont start the fire in the middle. And nothing happens after solving all three.

**Comment by Terekyy** [comment]
![Screenshot_20](https://user-images.githubusercontent.com/109367635/179583253-ed53a480-711f-4fb8-9f4b-ed84c1955e20.png)

**Comment by yungnickyoung** [comment]
Try turning the lights off :)

**Comment by Terekyy** [comment]
Wait, that worked! I googled and the videos I watched told me to solve the puzzles by lighting the fires. Oh well, thank you!
