### ISSUE TITLE
[Forge] TPS lag spikes every second with Farmers' Delight

### ISSUE THREAD

**Issue by Insane96** [YUNG-GANG/YUNGs-Better-Desert-Temples#8]
YungsBetterDesertTemples-1.18.2-Forge-1.3
Forge 40.1.60

When playing I'm getting TPS lag spikes every second.
By using spark I've traced the problem to a ServerPlayer mixin injection (by checking the code the mixin is executed every second) and removing the mod resulted in no more tps lag spikes.

https://spark.lucko.me/hVksWap6KK
This seems to be the problematic line
https://github.com/YUNG-GANG/YUNGs-Better-Desert-Temples/blob/multiloader/1.18/Common/src/main/java/com/yungnickyoung/minecraft/betterdeserttemples/mixin/ServerPlayerTickMixin.java#L72

**Comment by yungnickyoung** [comment]
This line should be fine on its own - can you try figuring out which mod(s) must be present for the issue to occur?

**Comment by Insane96** [comment]
Tested by disabling mods and Farmer's delight's the culprit. 

FarmersDelight-1.18.2-1.1.2.jar
YungsBetterDesertTemples-1.18.2-Forge-1.3.jar

**Comment by yungnickyoung** [comment]
Please try with v1.3.1 and see if the issue persists!

**Comment by Mindtester** [comment]
Had similar issue and had to disable fatigue in config. But spikes were more sporadic and observed only playing on server (fabric).
With 1.3.1 and fatigue option turned on there were no such lag spikes yet.

**Comment by MarioSMB** [comment]
Perhaps it would be better to use the vanilla mechanic of applying mining fatigue - that is, have the boss give players the effect when nearby similar to the elder guardians. Ticking over areas and checking to see if the players have cleared them seems like a very performance intensive means of applying the effect.

**Comment by Insane96** [comment]
Ops, forgot to update.
Yes, with latest Forge update the lag spikes seem gone
